#!/bin/bash
#
# validate that commit message contains "valid" JIRA issue number

# regex to validate in commit msg
commit_regex='([A-Za-z]+-[0-9]+|^override|^merge)'
error_msg="Aborting commit. Your commit message must contain a valid JIRA issue number (ex: PROJ-1680)"

if ! grep -iqE "$commit_regex" "$1"; then
  echo "$error_msg" >&2
  exit 1
else

  # if commit message starts with merge of override, no need to validate JIRA issue
  commit_regex='(^override|^merge)'
  if grep -iqE "$commit_regex" "$1"; then
    exit 0
  fi

  # regex to parse each JIRA issue, but too complicated for git commit
  #msg="JIRA-111 includes JIRA-222"
  re='[[:upper:]]+-[[:digit:]]+' 
  while read -r msg; do
    while [[ $msg =~ $re ]]; do 
      #echo ${BASH_REMATCH[0]}
      HTTP_STATUS=$(curl -u api-user:"FK\}N\?E8X5qt" -s -o /dev/null -w "%{http_code}" https://smarsh.atlassian.net//rest/api/latest/issue/${BASH_REMATCH[0]})
      if [ $HTTP_STATUS -ne 200 ]; then
        echo "Aborting commit. Invalid JIRA issue specified : ${BASH_REMATCH[0]]}"
        exit 1
      fi
      msg=${msg#*"${BASH_REMATCH[0]}"} 
    done
  done < $1
fi

# success, commit
exit 0
